json endpoint active
ackao/ffxiv-dps-calc pull request #11
Opened 2021-03-30 09:59 UTC by joooooooooe-star

adds very crude json acceptance for endpoint

2021-03-30 10:00 UTC, joooooooooe-star commented on backend/main.py
> +        return "abort", abort(400)
this is probably wrong

2021-03-30 10:01 UTC, joooooooooe-star commented on backend/main.py
> +    # Convert job strings to enum
i made a useless comment

2021-04-04 18:18 UTC, ackao requested changes

2021-04-04 18:18 UTC, ackao commented on backend/pps/sch.py
> +class SchPps:
accel's thing got merged in, can use that now

2021-04-04 18:18 UTC, ackao commented on backend/main.py
> +    job_string_to_enum = {
pull this out into a separate helper function, we'll want this for other stuff i assume

2021-04-04 18:19 UTC, ackao commented on backend/pps/sch.py
> +class SchPps:
oh hey i was able to just merge it in, ez

2021-04-04 18:20 UTC, ackao commented on backend/main.py
> +    job_string_to_enum = {
god damn it i looked at an outdated version

2021-04-04 18:21 UTC, ackao approved these changes

2021-04-04 18:21 UTC, merged